# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 50 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
# highlighter: pygments
highlighter: rouge
markdown: kramdown
disqus: linzhanyu
google_analytics: linzhanyu
title: 林占宇

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 小蘑菇的奇幻森林

description: Stylish Jekyll Theme
author:
  name: linzhanyu
  email: linzhanyu@gmail.com
  github: linzhanyu
  facebook: zhanyu.lin.7
  twitter: linzhanyu
  pinterest: linzhanyu
  linkedin: 占宇-林-895753126
  bio: <br>Linux, VIM, OpenGL, OpenCL.<br><br>Python, C++, C#, ML.<br><br>相看莫相笑，同是竹林人。<br><br>
  # email_md5: 726351295ec82e145928582f595aa3aa
  email_md5: 605738211f1571f2de300c6ce81c44a8

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

url: "https://linzhanyu.github.io"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mermaid

mermaid:
  src: /assets/js/mermaid.min.js
  # src: 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.0.0/mermaid.min.js'

